<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\logo.ico</ApplicationIcon>
    <AssemblyName>İzin Programı</AssemblyName>
    <RootNamespace>$(MSBuildProjectName.Replace(" ", "_"))</RootNamespace>
    <PackageId>İzin Programı</PackageId>
    <Title>İzin Programı</Title>
    <Company>Kara Holding</Company>
    <Product>İzin Programı</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\LeaveManager.Core\LeaveManager.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\logo.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
